import { Express, Request, Response } from 'express';
import swaggerUi from 'swagger-ui-express';
import fs from 'fs';
import path from 'path';

// Parse package.json to get version and title
const packageJson = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf-8'));

export const swaggerDocs = (app: Express, port: number | string) => {
  // Simple JSON definition for now (Expandable to use swagger-jsdoc if needed)
  const swaggerDefinition = {
    openapi: '3.0.0',
    info: {
      title: packageJson.name || 'API Docs',
      version: packageJson.version || '1.0.0',
      description: 'API Documentation generated by CODENUB',
    },
    servers: [
      {
        url: `http://localhost:${port}`,
        description: 'Local Server',
      },
    ],
    paths: {
      '/': {
        get: {
          summary: 'Health Check',
          responses: {
            200: {
              description: 'App is running',
            },
          },
        },
      },
    },
  };

  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDefinition));

  console.log(`📄 Docs available at http://localhost:${port}/docs`);
};
